# Generated by Django 4.0.4 on 2023-03-19 12:32

from django.db import migrations, models
import django.db.models.deletion
import sound_sorting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(default='REAL', max_length=6)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_folders', to='sound_sorting.gamefolder')),
            ],
            options={
                'unique_together': {('name', 'parent_folder')},
            },
        ),
        migrations.CreateModel(
            name='SoundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sound_file', models.FileField(upload_to=sound_sorting.models.get_sound_upload_dest)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_sounds', to='sound_sorting.gamefolder')),
            ],
        ),
    ]
