# Generated by Django 4.0.4 on 2023-03-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound_sorting', '0002_sounditemreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sounditemreview',
            name='sound',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sound_reviews', to='sound_sorting.sounditem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamefolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_folders', to='sound_sorting.gamefolder'),
        ),
    ]
