# Generated by Django 4.0.4 on 2023-03-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        ('sound_sorting', '0003_sounditemreview_sound_alter_gamefolder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sounditem',
            unique_together={('name', 'parent_folder')},
        ),
        migrations.AlterUniqueTogether(
            name='sounditemreview',
            unique_together={('user_profile', 'sound')},
        ),
    ]
