# Generated by Django 4.0.4 on 2023-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_sorting', '0005_alter_sounditemreview_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounditemreview',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sound_reviews', to='sound_sorting.soundcategory'),
        ),
        migrations.AlterField(
            model_name='sounditemreview',
            name='is_useful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
