# Generated by Django 4.0.4 on 2023-03-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_sorting', '0007_remove_sounditem_sound_file_sounditem_gdrive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sounditem',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sounditem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
